## Python Matriks dan NumPy Array

---

Matriks adalah struktur data dua dimensi di mana angka-angka disusun menjadi baris dan kolom. Contohnya :

<img src="https://cdn.programiz.com/sites/tutorial2program/files/matrix.jpg">

Matriks ini adalah matriks 3x4 (dibaca "tiga kali empat") karena memiliki 3 baris dan 4 kolom.

### Python Matriks
Python tidak memiliki tipe built-in untuk matriks. Namun, kita dapat memperlakukan list di dalam list sebagai matriks. Sebagai contoh:

In [ ]:
A = [[1, 4, 5], 
    [-5, 8, 9]]

Kita dapat memperlakukan list ini sebagai matriks yang memiliki 2 baris dan 3 kolom.
<img src="https://cdn.programiz.com/sites/tutorial2program/files/matrix-python-example.jpg">

**Contoh Program**

In [ ]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

Untuk mencetak atau mendapatkan seluruh nilai yang ada pada matriks di atas dapa digunakan perintah :

In [ ]:
print("A =", A)

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]


Selain itu, kita juga dapat mendapatkan elemen tertentu dari matriks tersebut dengan cara :

In [ ]:
print("A[1] =", A[1])      # Baris ke-2

print("A[1][2] =", A[1][2])   # Elemen ke-3 dari baris ke-2

print("A[0][-1] =", A[0][-1])   # Elemen terakhir dari Baris ke-1

A[1] = [-5, 8, 9, 0]
A[1][2] = 9
A[0][-1] = 12


---
### NumPy Array
NumPy adalah sebuah library untuk komputasi ilmiah yang memiliki dukungan untuk objek array berdimensi-N. NumPy menyediakan deretan angka multidimensi (yang sebenarnya adalah sebuah objek). Contohnya:

In [ ]:
import numpy as np

a = np.array([1, 2, 3])

print(a)               

print(type(a))         

[1 2 3]
<class 'numpy.ndarray'>


Seperti yang Anda lihat, kelas array NumPy disebut ndarray.

---

### Bagaimana cara membuat array NumPy?
Ada beberapa cara untuk membuat array NumPy.

1. Array bilangan bulat, float dan Bilangan kompleks

In [ ]:
A = np.array([[1, 2, 3], [3, 4, 5]]) # Bilangan bulat
print(A)

[[1 2 3]
 [3 4 5]]


In [ ]:
A = np.array([[1.1, 2, 3], [3, 4, 5]]) # float
print(A)

[[1.1 2.  3. ]
 [3.  4.  5. ]]


In [ ]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # bilangan kompleks
print(A)

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


---
2. Array angka nol dan satu

In [ ]:
zeroes_array = np.zeros( (2, 3) )
print(zeroes_array)

[[0. 0. 0.]
 [0. 0. 0.]]


Selain itu, kita juga dapat menetapkan `dtype` menjadi 32 bit (4 byte). Karenanya, array ini dapat mengambil nilai dari <code>-2<sup>-31</sup></code> hingga <code>2<sup>-31</sup>-1</code>.

In [ ]:
ones_array = np.ones( (1, 5), dtype=np.int32 ) # menentukan dtype
print(ones_array)

[[1 1 1 1 1]]


---

### Operasi Matriks

Pada contoh program selanjutnya akan dibuat 3 jenis program yaitu : penjumlahan dua buah matriks, perkalian dua buah matriks dan transpos sebuah matriks. Jika menggunakan program python biasa, kita memerlukan `nested lists` untuk membuat program tersebut. Namun ada cara yang lebih baik yaitu menggunakan library NumPy.

#### Penambahan Dua Matriks

<img src="https://i1.faceprep.in/Companies-1/matrix-addition-in-python.png" width="35%">
Kita dapat menggunakan operator `+` untuk menambahkan elemen yang sesuai dari dua matriks NumPy.

In [ ]:
A = np.array(
    [[3, 4], 
     [2, 1]])

B = np.array(
    [[1, 5], 
     [3, 7]])

C = A + B   

print(C)

[[4 9]
 [5 8]]


---
#### Perkalian Dua Matriks

<img src="https://i1.faceprep.in/Companies-1/matrix-multiplication-in-python.png" width="40%">
Untuk mengalikan dua matriks, kita menggunakan metode `dot()`. 

**Catatan**: `*` digunakan untuk perkalian array (perkalian elemen yang sesuai dari dua array) bukan perkalian matriks.

In [ ]:
A = np.array(
    [[3, 4], 
     [2, 1]])

B = np.array(
    [[1, 5], 
     [3, 7]])

C = A.dot(B)

print(C)

[[15 43]
 [ 5 17]]


---
#### Transpos Matriks

<img src="https://i1.faceprep.in/Companies-1/transpose-of-a-matrix-in-python.png" width="35%">
Kita dapat menggunakan `numpy.transpose` untuk menghitung transpos matriks.

In [ ]:
A = np.array(
    [[3, 4], 
     [2, 1]])

print(A.transpose())

[[3 2]
 [4 1]]


---

## Tugas
Pada contoh program di atas, sudah di buat 3 program dengan memanfaatkan library NumPy yaitu : 
1. Penambahan dua matriks
2. Perkalian dua matriks
3. Transpos matriks

Tugas anda adalah membuat 3 program tersebut tanpa menggunakan library NumPy.

---

# 1. Penambahan dua matriks

In [ ]:
# ANGKANYA GANTI, JANGAN SAMA
X = [[0,2,3],
     [4,3,1],
     [0,3,7]]

# ANGKANYA GANTI, JANGAN SAMA
Y = [[1,2,3],
     [2,3,6],
     [1,2,9]]

result = [[0 for j in range(len(X[0]))] for i in range(len(X))]
for i in range(len(X)):
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

print('\nMATRIX 1:')
for r in X:
   print(r)

print('\nMATRIX 2:')
for r in Y:
   print(r)

print('\nHASIL:')
for r in result:
   print(r)



MATRIX 1:
[0, 2, 3]
[4, 3, 1]
[0, 3, 7]

MATRIX 2:
[1, 2, 3]
[2, 3, 6]
[1, 2, 9]

HASIL:
[1, 4, 6]
[6, 6, 7]
[1, 5, 16]


# 2. Perkalian dua matriks

In [ ]:
# ANGKANYA GANTI, JANGAN SAMA
X = [[10,8,3],
    [4 ,6,9],
    [7 ,3,6]]

# ANGKANYA GANTI, JANGAN SAMA
Y = [[5,6,2,7],
    [6,4,2,0],
    [4,6,7,1]]

result = [[0 for j in range(len(Y[0]))] for i in range(len(X))]

for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

print('\nMATRIX 1:')
for r in X:
   print(r)

print('\nMATRIX 2:')
for r in Y:
   print(r)

print('\nHASIL:')
for r in result:
   print(r)


MATRIX 1:
[10, 8, 3]
[4, 6, 9]
[7, 3, 6]

MATRIX 2:
[5, 6, 2, 7]
[6, 4, 2, 0]
[4, 6, 7, 1]

HASIL:
[110, 110, 57, 73]
[92, 102, 83, 37]
[77, 90, 62, 55]


# 3. Transpos matriks

In [ ]:
# ANGKANYA GANTI, JANGAN SAMA
X = [[15,6],
    [4 ,8],
    [3 ,7]]

result = [[0 for j in range(len(X))] for i in range(len(X[0]))]

for i in range(len(X)):
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

print('\nSEBELUM TRANSPOS:')
for r in X:
   print(r)

print('\nSESUDAH TRANSPOS:')
for r in result:
   print(r)


SEBELUM TRANSPOS:
[15, 6]
[4, 8]
[3, 7]

SESUDAH TRANSPOS:
[15, 4, 3]
[6, 8, 7]
